export const ADD_TO_CART = 'ADD_TO_CART';
export const MENU_FETCH_BEGIN = 'MENU_FETCH_BEGIN';
export const INGREDIENTS_FETCH_SUCCESS = 'INGREDIENTS_FETCH_SUCCESS';
export const MENU_FETCH_SUCCESS = 'MENU_FETCH_SUCCESS';
export const CLEAR_CART = 'CLEAR_CART';
